"""
app/services/listing_service.py
Raw-SQL service for Listing CRUD.
"""

from decimal import Decimal
from typing import Optional

from fastapi import HTTPException, status

from app.db.connection import get_connection, cursor_execute, last_insert_id


def create_listing(
    u_id: int,
    c_id: int,
    title: str,
    description: Optional[str],
    price: Decimal,
    cond: str,
    listing_type: str,
) -> dict:
    """
    Insert a listing.
    Matching-alert notifications are generated by the database trigger.
    """
    if listing_type != "sell":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Public listings support sell items only. Use alerts for buy requests.",
        )

    with get_connection() as conn:
        cursor = conn.cursor(dictionary=True)
        try:
            cursor_execute(
                cursor,
                """
                INSERT INTO Listing (u_id, c_id, title, description, price, cond, type, status)
                VALUES (%s, %s, %s, %s, %s, %s, %s, 'active')
                """,
                (u_id, c_id, title, description, float(price), cond, listing_type),
            )
            listing_id = last_insert_id(cursor)
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            cursor.close()

    return get_listing_by_id(listing_id)


def get_listings(
    listing_type: Optional[str] = None,
    c_id: Optional[int] = None,
    price_min: Optional[Decimal] = None,
    price_max: Optional[Decimal] = None,
    status: Optional[str] = "active",
) -> list[dict]:
    """
    Fetch listings with optional filters.
    """
    sql = """
        SELECT  l.listing_id,
                l.u_id,
                l.c_id,
                l.title,
                l.description,
                l.price,
                l.cond,
                l.type,
                l.status,
                l.created_at,
                u.username  AS seller_username,
                c.name      AS category_name
        FROM    Listing  l
        JOIN    Users    u ON u.u_id  = l.u_id
        JOIN    Category c ON c.c_id  = l.c_id
        WHERE   1 = 1
    """
    params: list = []

    if status:
        sql += " AND l.status = %s"
        params.append(status)

    if listing_type == "buy":
        return []

    sql += " AND l.type = 'sell'"

    if c_id is not None:
        sql += " AND l.c_id = %s"
        params.append(c_id)

    if price_min is not None:
        sql += " AND l.price >= %s"
        params.append(float(price_min))

    if price_max is not None:
        sql += " AND l.price <= %s"
        params.append(float(price_max))

    sql += " ORDER BY l.created_at DESC"

    with get_connection() as conn:
        cursor = conn.cursor(dictionary=True)
        cursor_execute(cursor, sql, tuple(params))
        rows = cursor.fetchall()
        cursor.close()

    return rows


def get_listing_by_id(listing_id: int) -> dict:
    """
    Fetch a single listing with seller and category details.
    """
    with get_connection() as conn:
        cursor = conn.cursor(dictionary=True)
        cursor_execute(
            cursor,
            """
            SELECT  l.listing_id,
                    l.u_id,
                    l.c_id,
                    l.title,
                    l.description,
                    l.price,
                    l.cond,
                    l.type,
                    l.status,
                    l.created_at,
                    u.username  AS seller_username,
                    c.name      AS category_name
            FROM    Listing  l
            JOIN    Users    u ON u.u_id = l.u_id
            JOIN    Category c ON c.c_id = l.c_id
            WHERE   l.listing_id = %s
            """,
            (listing_id,),
        )
        row = cursor.fetchone()
        cursor.close()

    if not row:
        raise HTTPException(status_code=404, detail="Listing not found")
    return row


def update_listing(listing_id: int, u_id: int, updates: dict) -> dict:
    """
    Dynamically build SET clause and update only provided fields.
    """
    fields = {k: v for k, v in updates.items() if v is not None}
    if not fields:
        raise HTTPException(status_code=400, detail="No fields to update")

    set_clauses = ", ".join(f"{col} = %s" for col in fields)
    params = list(fields.values()) + [listing_id, u_id]

    with get_connection() as conn:
        cursor = conn.cursor()
        cursor_execute(
            cursor,
            f"UPDATE Listing SET {set_clauses} WHERE listing_id = %s AND u_id = %s",
            tuple(params),
        )
        if cursor.rowcount == 0:
            conn.rollback()
            raise HTTPException(
                status_code=403,
                detail="Listing not found or you are not the owner",
            )
        conn.commit()
        cursor.close()

    return get_listing_by_id(listing_id)


def delete_listing(listing_id: int, u_id: int) -> dict:
    """
    Soft-delete: set status = 'closed' (owner only).
    """
    with get_connection() as conn:
        cursor = conn.cursor()
        cursor_execute(
            cursor,
            "UPDATE Listing SET status = 'closed' WHERE listing_id = %s AND u_id = %s",
            (listing_id, u_id),
        )
        if cursor.rowcount == 0:
            conn.rollback()
            raise HTTPException(
                status_code=403,
                detail="Listing not found or you are not the owner",
            )
        conn.commit()
        cursor.close()

    return {"listing_id": listing_id, "status": "closed"}
